// <auto-generated />
namespace Event.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _13042016Wind2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_13042016Wind2));
        
        string IMigrationMetadata.Id
        {
            get { return "201604130849131_13-04-2016-Wind2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
