all:

clean:
	rm -rf *.aux *.blg *.bbl *.log *.out *.synctex.gz *.toc DistributedConsensus.pdf
	rm -rf 1introduction/*.aux 2background/*.aux 3local/*.aux 4connect/*.aux 5validation/*.aux 6orderofexecution/*.aux 7previous/*.aux 8conclusion/*.aux
